# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        cyber range: 1
        incident response: 1
        log analysis: 1
        log based: 1
        web security: 1
        zero-day: 1
        security: 1
        cybersecurity: 1
        container: 1
        cloud native: 1
        docker: 1
        kubernetes: 1
        virtualization: 1
        malware: 1
        computer network: 1
        TCP: 1
        openid: 1
        oauth: 1
        authorization: 1
        authentication: 1
        threat: 1
        phishing: 1
        devsecops: 1
        wireless network: 1
        wsn: 1
        dos: 1
        neural network: -999

# 通知の閾値
score_threshold: 0
